# metadata
run_name: 'map_wide'
# characteristic number for map
perf_num: 6

# map paths
map_path: './maps/SOCHI'
map_ext: '.png'

# starting pose for map
p1:
  sx:  -1.0
  sy:  0.0
  stheta: 4.1421595 #1.37079632679
p2:
  sx:  0.5
  sy:  -0.5
  stheta: 4.1421595 #1.37079632679
p3:
  sx:  0.0
  sy:  0.0
  stheta: 4.1421595 #1.37079632679
p4:
  sx:  -0.5
  sy:  0.5
  stheta: 4.1421595 #1.37079632679

# raceline path and indices
wpt_path: './maps/SOCHI.csv'
wpt_delim: ';'
wpt_rowskip: 3
wpt_xind: 1
wpt_yind: 2
wpt_thind: 3
wpt_vind: 5

# render params
render_waypoints: True
render_center: True
render_mode: 'human' # or 'human_fast'

# vehicle params
mass: 3.463388126201571
lf: 0.15597534362552312


# Planner set speed
max_speed: 4.0
min_speed: 4.0

# varied params bound
# physical params
mass_min: 3.0
mass_max: 4.0
lf_min: 0.147
lf_max: 0.170
# controller params
tlad_min: 0.2
tlad_max: 5.
vgain_min: 0.5
vgain_max: 1.5

# computation budget (can think of it as gen_num times pop_size)
popsize: 100
budget: 1000

# optimization method
optim_method: 'CMA'

# seed
seed: 12345